[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ah_openai"
version = "1.0.0"
description = "A module for OpenAI integration"
requires-python = ">=3.7"
dependencies = [
    "openai>=1.66.3",
    "python-dotenv",
    "nanoid",
    "simpleaudio"
]

